{{- if not .Values.disabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    application.giantswarm.io/team: {{ .Values.team }}
    {{- include "aws-ebs-csi-driver-servicemonitors.labels" . | nindent 4 }}
  name: aws-ebs-csi-driver-controller
  namespace: kube-system
spec:
  endpoints:
    - port: http
  selector:
    matchLabels:
      app: ebs-csi-controller
{{- end }}
